name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Set up MemKernel as a module (M-OUT) with specified name
      run: |
       curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s M Starqltechn

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Starqlte
      with:
        arch: arm64
        compiler: clang/11
        defconfig: starqlte_chn_open_defconfig
        image: Image.gz-dtb
      # Simpan log build ke dalam file
      run: |
        ./build_kernel.sh > build.log 2>&1 || true

    - name: Upload Kernel, Module, and Logs
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build-artifacts
        path: |
          ${{ steps.build.outputs.outfile }}
          ./out/drivers/memkernel/memkernel.ko
          build.log
